- name: Configure Frontend Server
  hosts: frontend-server
  become: yes  # This allows privilege escalation (sudo)

  tasks:
    - name: Install NGINX (Only if OS is Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - curl
        - git
